src/project/urls.py
from django.contrib import admin
from django.urls import path, include

#動画読み込み用モジュール
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chapter_app.urls'))
]

# メディアファイル読み込み用URL設定
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/chapter_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from mdeditor.fields import MDTextField


#ユーザーテーブルを定義
class User(AbstractUser):
    email = models.EmailField(max_length=100, unique=True)
    
    def __str__(self):
        return self.username

# 動画テーブル
class Video(models.Model):   
    def video_upload_path(instance, filename):
        ext = filename.split('.')[-1]
        return f"storage/videos/video_{instance.id}.{ext}"
     
    user = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=1)
    video_title = models.CharField(max_length=256, unique=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, default='処理順番待ち')
    video_path = models.FileField(upload_to=video_upload_path)
    thumbnail_path = models.CharField(max_length=256, null=True)
    transcription_path = models.CharField(max_length=256, null=True)

    def save(self, *args, **kwargs):
        if self.id is None:
        # アップロードされたファイルを変数に代入しておく
            uploaded_file = self.video_path

            # 一旦fileフィールドがNullの状態で保存(→インスタンスIDが割り当てられる)
            self.video_path= None
            super().save(*args, **kwargs)

            # fileフィールドに値をセット
            self.video_path = uploaded_file
            if "force_insert" in kwargs:
                kwargs.pop("force_insert")

        # この段階ではインスタンスIDが存在するので、_file_upload_path関数でinstance.idが使える
        super().save(*args, **kwargs)


# チャプターテーブル
class Chapter(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    chapter_text = models.TextField(default='チャプター生成中')
    updated_at = models.DateTimeField(auto_now=True)


# 要約テーブル
class Summary(models.Model):
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    summary_text = MDTextField(default='## 要約生成中')
    updated_at = models.DateTimeField(auto_now=True)
    
    

src/chapter_app/forms.py
from django import forms
# デフォルトのUserモデルを外す
# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
# カスタムのUserモデルを適用
from .models import User, Video, Chapter, Summary

#ファイル拡張子を指定
from django.core.validators import FileExtensionValidator 

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class LoginForm(AuthenticationForm):
    pass

class UploadForm(forms.ModelForm):
    video_path = forms.FileField(widget=forms.FileInput(attrs={'accept':'.mp4'}), label='動画ファイル')
    class Meta:
        model=Video
        fields=['video_title', 'video_path']
        labels={
           'video_title':'タイトル',
           }

    def clean_video_title(self):
        video_title = self.cleaned_data.get('video_title')

        #既存の動画と重複しているかチェック
        if Video.objects.filter(video_title=video_title).exists():
            raise forms.ValidationError('同じタイトルが既に存在しています。')
                
        return video_title

class VideoForm(forms.ModelForm):
    class Meta:
        model=Video
        fields=[
            'video_title',
        ]
        labels = {
            'video_title' : '動画タイトル'
        }

class ChapterForm(forms.ModelForm):         
    class Meta:
        model=Chapter
        fields=[
            'chapter_text',
        ]
        labels = {
            'chapter_text': 'チャプター'
        }
       
    
class SummaryForm(forms.ModelForm):
    class Meta:
        model=Summary
        fields=[           
            'summary_text'
        ]

src/templates/base-top.html
<!-- CSS読み込み -->
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}" />

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- title -->
    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    <!-- header -->
    <header>{% block header %} {% endblock header %}</header>

    <!-- main -->
    <main>{% block main %} {% endblock main %}</main>
  </body>
</html>

src/templates/base.html
<!-- CSS読み込み -->
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}" />

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- title -->
    <title>{% block title %} {% endblock title %}</title>
    {% block meta %} {% endblock meta %}
  </head>
  <body>
    <!-- header -->
    <header>
      {% block header %} {% endblock header %}
      <ul class="navbar">
        <li>
          <a href="{% url 'logout'%}">ログアウト</a>
        </li>
        {% if user.is_staff %}
        <li>
          <a href="{% url 'upload'%}">動画アップロード</a>
        </li>
        {% endif %}
        <li>
          <a href="{% url 'main'%}">動画一覧</a>
        </li>
        <li>
          <a href="{% url 'user'%}">アカウント管理</a>
        </li>
      </ul>
    </header>

    {% if messages %}
      {% for message in messages %}
        <p class="message">{{ message }}</p>
      {% endfor %}
    {% endif %}

    <!-- main -->
    <main>
      {% block main %} {% endblock main %}
    </main>
  </body>
</html>

src/templates/chapter_edit.html
{% extends 'base.html' %}

{% block title %}チャプター編集{% endblock %}

{% block main %}
  <style>
    .video-wrapper {
      grid-row: 2 / 3;
      grid-column: 1 / 2;
      margin-top: 30px;
    }

    video {
      width: 100%; 
      height: auto;
    }

    .video-info {
      margin-top: 1rem;
      font-weight: bold;
    }

    .chapter-wrapper {
      grid-column: 2 / 3;
      height:100%;
      margin-top: 30px;
      margin-left: 30px;
    }

    .chapter-text {
      overflow: auto;
      width: 100%;
      height:100%;
      line-height: 1.8em;
    }

    .form-wrapper {
      grid-column: 3 / 4;
      height:100%;  
      margin-top: 30px;
      margin-left: 30px;  
    }

    form {
      width:100%;
      height: 100%;
    }

    #id_video_title {
      padding: 0.3em;
      font-size:1.5em;
      margin-bottom: 10px;
    }

    #id_chapter_text {
      border-radius: 10px;
      padding: 0.5em;
      line-height: 1.8em;
      font-size:1.2em;
      resize: none;
      width: 100%;
      height:70%;
    }
  </style>

  <div class="title-menu-wrapper">
    <h1 class="video-title">{{ video.video_title }}</h1>
    <a href="{% url 'video' video.id %}" class="menu-button">動画閲覧</a>
    <a href="{% url 'summary' video.id %}" class="menu-button">要約</a>
    {% if video.transcription_path %}
      <a href="{% url 'download_transcription' video.id %}" class="menu-button">文字起こしダウンロード</a>
    {% endif %}
  </div>

  <div class="video-wrapper">
    <video
      controls
      preload="auto"
      playsinline
      src="{{ video.video_path.url }}"
      id="videoPlayer"
      poster="{{ video.thumbnail_path }}"
    >動画は再生できません。</video>
    <div class="video-info">
      <p>動画投稿日時：{{ video.uploaded_at }}</p>
      <p>投稿者：{{ video.user.username }}</p>
    </div>
  </div>

    <div class="chapter-wrapper">
      <div class="chapter-text">
        {% for line in chapter_lines %}
          <p><a href="#" class="chapter-link">{{ line }}</a></p>
        {% endfor %}
      </div>
    </div>

    <div class="form-wrapper">
      <form method="POST">
        {% csrf_token %} 
        {{ video_form.as_p }}
        {{ chapter_form.as_p }}
        <button type="submit" class="submit-button">保存</button>
      </form>
    </div>


    <script>
      document.addEventListener("DOMContentLoaded", function () {
        // チャプターリンクにイベントリスナーを設定
        var chapterLinks = document.querySelectorAll(".chapter-link");
        chapterLinks.forEach(function (link) {
          link.addEventListener("click", function (event) {
            event.preventDefault();
            var timeString = this.textContent.match(/\[(\d{2}:\d{2}:\d{2})\]/)[1];
            jumpTo(timeString);
          });
        });
      });

      function jumpTo(timeString) {
        var video = document.getElementById("videoPlayer");
        var parts = timeString.split(":");
        var hours = parseInt(parts[0]);
        var minutes = parseInt(parts[1]);
        var seconds = parseInt(parts[2]);

        // 総秒数を計算
        var totalSeconds = hours * 3600 + minutes * 60 + seconds;

        // 動画を指定された時間にジャンプ
        video.currentTime = totalSeconds;
        video.play();
      }

      function flexTextarea(el) {
  const dummy = el.querySelector('.FlexTextarea__dummy')
  el.querySelector('.FlexTextarea__textarea').addEventListener('input', e => {
    dummy.textContent = e.target.value + '\u200b'
  })
}

document.querySelectorAll('.FlexTextarea').forEach(flexTextarea)
    </script>

{% endblock %}

src/templates/edit.html
{% extends 'base.html' %}

<head>
  {% block title %}編集ページ{% endblock %}
</head>

<body>
  {% block header %}
  <style>
    main {
      grid-row: 2 / 3;
      grid-column: 2 / 5;
      padding: 50px;
    }

    .video-and-chapters-container {
      display: grid;
      grid-template-columns: 1fr 2fr 2fr 1fr;
    }

    .video-wrapper {
      grid-column: 2 / 3;
    }

    .chapters-wrapper {
      grid-column: 3 / 4;
      padding-left: 70px;
    }

    .chapter-text {
      overflow: auto;
      width: 100%;
      height:250px;
    }

    .form-wrapper {
      width: 50%;
      margin-top: 20px;
      margin-left: auto;
      margin-right: auto;
    }

    #id_chapter_data {
      resize: none;
      width: 100%;
    }
  </style>
  {% endblock header%} 
  {% block main %}
  {% if chapter.video_path != null %}
  <div class="video-and-chapters-container">
    <div class="video-wrapper">
      <video
        controls
        preload="auto"
        playsinline
        src="{{ chapter.video_path.url }}"
        style="width: 100%; height: auto"
        id="videoPlayer"
      ></video>
    </div>

    <div class="chapters-wrapper">
      <h3>タイトル：{{ chapter.video_title }}</h3>
      <div class="chapter-text">
        {% for line in chapter_lines %}
          <p><a href="#" class="chapter-link">{{ line }}</a></p>
        {% endfor %}
      </div>
    </div>

    <script>
      document.addEventListener("DOMContentLoaded", function () {
        // チャプターリンクにイベントリスナーを設定
        var chapterLinks = document.querySelectorAll(".chapter-link");
        chapterLinks.forEach(function (link) {
          link.addEventListener("click", function (event) {
            event.preventDefault();
            var timeString = this.textContent.match(/\[(\d{2}:\d{2}:\d{2})\]/)[1];
            jumpTo(timeString);
          });
        });
      });

      function jumpTo(timeString) {
        var video = document.getElementById("videoPlayer");
        var parts = timeString.split(":");
        var hours = parseInt(parts[0]);
        var minutes = parseInt(parts[1]);
        var seconds = parseInt(parts[2]);

        // 総秒数を計算
        var totalSeconds = hours * 3600 + minutes * 60 + seconds;

        // 動画を指定された時間にジャンプ
        video.currentTime = totalSeconds;
        video.play();
      }
    </script>
  </div>
  {% endif %}
  <div class="form-wrapper">
    <form method="POST">
      {% csrf_token %} {% for field in form %}
      <div class="fieldWrapper">
        {{ field.errors }} {{ field.label_tag }} {{ field }}
      </div>

      {% endfor %}

      <button type="submit" class="ui button">保存</button>

      <p><strong>作成日時:</strong> {{ chapter.created_at }}</p>
      <p><strong>更新日時:</strong> {{ chapter.updated_at }}</p>
      <p><strong>作成者:</strong> {{ chapter.user.username }}</p>
    </form>
    {% if chapter.transcription_path %}
      <div style="text-align:right;">
        <a href="{% url 'download_transcription' chapter.id %}">文字起こしテキストをダウンロード</a></div>
      </div>
    {% endif %}
  {% endblock %}
</body>

src/templates/login.html
{% extends 'base-top.html' %} {% load static %}

{% block title %}ログイン{% endblock title %}

{% block main %}
<style>
  .login-wrapper {
    grid-row: 2 / 3;
    grid-column: 2 / 3;
  }

  h1 {
    margin-bottom: 20px;
    font-size: 3em;
    text-align: center;
  }

  #id_username {
    margin-bottom: 20px;
  }

  .login-button {
    display:flex;
    justify-content: center;
  }
 
  .circle-button {
    color: white;
    font-weight: bold;
    font-size: 1.5em;
    display: grid;
    justify-content: center;
    align-content: center;
    background-color: rgb(255, 136, 0);
    border: 2px solid rgb(255, 136, 0);
    border-radius: 50%;
    width: 120px;
    height: 120px;
    cursor: pointer;
    text-decoration: none;
    margin-top: 20px;
  }

  .circle-button:active {
    position: relative;
    top: 5px;
  }

  .login-info {
    grid-row: 1 / 3;
    grid-column: 3 / 4;
    height: auto;
    line-height: 2em;
    background-color: yellow;
    border: 2px solid yellow;
    margin-left: 50px;
  }

</style>
  <div class="login-wrapper">
    <h1>Video-Learn</h1>
    <form action="{% url 'login' %}" name="form1" method="post">
      {% csrf_token %}
      <!-- form挿入 -->
      {{ form.as_p }}
      <p><input type="hidden" name="next" value="{{next}}" /></p>
      <div class="login-button">
        <button type="submit" class="circle-button">ログイン</button>
      </div>
    </form>
    <h3><a href="/admin/" class="admin">管理者用ページ</a></h3>
  </div>
  <div class="login-info">
    <h2>アクセス頂いた方へ</h2>
    <br>
    <h3>★講師アカウント</h3>
    <h4>　ユーザー名：teacher</h4>
    <h4>　パスワード：tea_pass</h4> 
    <p>　・動画のアップロードと視聴が可</b>能</p> 
    <p>　・チャプター、要約の編集が可能（※自分のアップロードした動画のみ。他のユーザーの上げた動画の編集はできません。）</p> 
    <h3>★生徒アカウント</h3>
    <h4>　ユーザー名：student</h4>
    <h4>　パスワード：stu_pass</h4>
    <p>　・動画の視聴、チャプター・要約の閲覧のみ可能</p>
    <br>
    <h3>※注意事項</h3>
    <p>　・動画アップロード後、チャプターと要約が生成されるまで数分〜数十分かかります。</p>
    <p>　　目安）30分動画で7~8分、2時間動画で30~40分ほど</p>
    <p>　・サンプルであがっている2本の動画はデジタル庁のYoutubeの動画です</p>
    <p><a href="https://youtu.be/mkyBxjGb2RQ">デジタル庁｜年次活動報告　2023年9月</a></p>
    <p><a href="https://youtu.be/vx1QrryxT2k ">「モビリティ・ロードマップ」のありかたに関する研究会（第６回）</a></p>
  </div>
{% endblock %}

src/templates/logout.html
{% extends 'base-top.html' %} {% load static %}

{% block title %}ログアウト{% endblock %}

{% block main %}
  <div class="main-container">
    <h1>ログアウトしました...</h1>
    <h2><a href="{% url 'login'%}">ログイン</a></h2>
  </div>
{% endblock main %}

src/templates/main.html
{% extends 'base.html' %} {% load static %}
{% block title %}チャプター一覧{% endblock title %} 

{% block meta %}
  <meta http-equiv="refresh" content="30; URL=" />
{% endblock meta %}

{% block main %}
  <style>
    .main-container {
      grid-column: 1 / 4;
      gap: 20px;
    }

    #tile-view, #table-view {
      background-color: #948080;
      color: #fff;
      border: 0;
      padding: 0.5em;
      border-radius: 5px;
      cursor: pointer;
      margin: 0 5px;
    }

    #table-container {
      display: none;
    }

    th, td {
      padding: 1em 2em;
      border: solid 1px #948080;   
    }

    table {
      width: auto;
      border-spacing: 0;
      border: 3px solid #948080;
      border-radius: 10px;
    }

    #tile-container {
      width:100%;
      display:flex;
      flex-wrap: wrap;
      align-content: flex-start;
      gap: 3%;
    }

    .tile-item {
      width: 17%;
      height: auto;
      line-height: 1.5em;
      border: 2px solid #948080;
      border-radius: 10px;
      margin-bottom: 2%;
    }

    .video-info-wrapper {
      margin:5px
    }

    img {
      width: 100%;
      height: 160px;
      border-radius: 10px 10px 0 0;
      margin-bottom: 5px;
    }
  </style>

  <div class="main-container">
    <h2>チャプター一覧</h2>
      <input
        type="text"
        id="searchInput"
        placeholder="キーワードで検索"
        style="width: 50%"
      />
      <div class="view-button">
        <button type="button" id="tile-view">サムネイル表示</button>
        <button type="button" id="table-view">テーブル表示</button>
      </div>

    <!-- テーブル表示用 -->
    <div id="table-container">
      <table id="Table">
        <tr class="trtop">
          <th>タイトル</th>
          <th>投稿者</th>
          <th>投稿日時</th>
          {% if user.is_staff %}
          <th>ステータス</th>
          {% endif %}
        </tr>
        {% for video in videos %}
        <tr height="40">
          <td align="center"><a href="{% url 'video' video.id %}">{{ video.video_title }}</a></td>
          <td align="center">{{ video.user.username }}</td>
          <td align="center">{{ video.uploaded_at }}</td>
          {% if user.is_staff %}
          <td align="center">{{ video.status }}</td>
          {% endif %}
        </tr>
        {% empty %}
        <tr height="40">
          <td>まだチャプターがありません</td>
          <td></td>
          <td></td>
          {% if user.is_staff %}
            <td></td>
          {% endif %}
        </tr>
        {% endfor %}
      </table>
    </div>

    <!-- サムネイル表示用 -->
    <div id="tile-container">
      {% for video in videos %}
      <div class="tile-item">
        <img src="{{ video.thumbnail_path }}">
        <div class="video-info-wrapper">
          <h3><a href="{% url 'video' video.id %}">{{ video.video_title }}</a></h3>
          <p>投稿者：{{ video.user.username }}</p>
          <p>投稿日時：{{ video.uploaded_at }}</p>
          {% if user.is_staff %}
          <p>ステータス：{{ video.status }}</p>
          {% endif %}
        </div>
      </div>
      {% empty %}
        <p>まだチャプターがありません</p>
      {% endfor %}
    </div>
  
  </div>

  <script>
    // サムネイル表示とテーブル表示の切り替え
    document.getElementById('tile-view').addEventListener('click', function(event) {
      document.getElementById('table-container').style.display = 'none';
      document.getElementById('tile-container').style.display = 'flex';
      document.cookie = 'view_style=tile';
      });

    document.getElementById('table-view').addEventListener('click', function(event) {
        document.getElementById('tile-container').style.display = 'none';
        document.getElementById('table-container').style.display = 'block';
        document.cookie = 'view_style=table';
    });

    // cookieからview_styleの値を取得し、それに基づいて表示を切り替え
    function getCookie(key) {
    const cookies = document.cookie.split(';');
    for (let cookie of cookies) {
        var cookiesArray = cookie.split('='); 
        if (cookiesArray[0].trim() == key.trim()) { 
            return cookiesArray[1];  // (key[0],value[1])
        }
    }
    return '';
    }

    let view_style = getCookie('view_style');
    if (view_style == 'table') {
      document.getElementById('tile-container').style.display = 'none';
      document.getElementById('table-container').style.display = 'block';
    } else if (view_style == 'tile') {
      document.getElementById('table-container').style.display = 'none';
      document.getElementById('tile-container').style.display = 'flex';
    }   

    

    // キーワード検索
    document.getElementById("searchInput").addEventListener("keyup", function () {
      let element = document.getElementById('table-container');
      let style = window.getComputedStyle(element);
      let value = style.getPropertyValue('display');
      if (value == 'block') {
      let searchValue = this.value.toLowerCase();
      let tableRows = document
        .getElementById("Table")
        .getElementsByTagName("tr");

      for (let i = 1; i < tableRows.length; i++) {
        let rowText = tableRows[i].textContent.toLowerCase();
        if (rowText.indexOf(searchValue) > -1) {
          tableRows[i].style.display = "";
        } else {
          tableRows[i].style.display = "none";
        }}
      } else {
      let searchValue = this.value.toLowerCase();
      let tileItems = document
        .getElementsByClassName("tile-item")

      for (let i = 0; i < tileItems.length; i++) {
        let tile = tileItems[i];
        let tileText = tile.textContent || tile.innerText;
        if (tileText.toLowerCase().indexOf(searchValue) > -1) {
          tileItems[i].style.display = "";
        } else {
          tileItems[i].style.display = "none";
        }
      }
    }});
  </script>
{% endblock main %}

src/templates/password_change.html
{% extends 'base.html' %} {% load static %}

{% block title %}パスワード変更{% endblock %}

{% block meta %} 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
{% endblock meta %}

{% block main %}
<style>
</style>

<div>
 {% csrf_token %} 
 {{ form.as_p }}
</div>

{% endblock main %}

src/templates/summary.html
{% extends 'base.html' %} {% load static %}
{% load markdown_extras %}

{% block title %}要約記事{% endblock %}

{% block meta %} 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link href="{% static 'mdeditor/css/editormd.min.css' %}" rel="stylesheet">
  <link href="{% static 'mdeditor/css/editormd.preview.css' %}" rel="stylesheet">
{% endblock meta %}

{% block main %}  
  <style>
    main {
      grid-template-columns: 1fr minmax(350px, 800px) 1fr;
    }

    .title-menu-wrapper {
      grid-column: 1 / 4;
      justify-content: center;
    }

   .summary-wrapper {
      grid-row: 2 / 3;
      grid-column: 2 / 3;
      padding: 10px;
      margin-top: 30px;
    }

    .editormd-preview-container, .editormd-html-preview {
      width: auto;
      margin: 10px
    }
  </style>

  <div class="title-menu-wrapper">
    <h1 class="video-title">{{ video.video_title }}</h1>
    {% if user == video.user %}
      <a href="{% url 'summary_edit' video.id %}" class="menu-button">要約編集</a>
    {% endif %} 
    <a href="{% url 'video' video.id %}" class="menu-button">動画閲覧</a>
    {% if video.transcription_path %}
      <a href="{% url 'download_transcription' video.id %}" class="menu-button">文字起こしダウンロード</a>
    {% endif %}
  </div>

  <div class="summary-wrapper">
    <div class="card-text pl-0 pr-0" id="content">
      {{ summary.summary_text | markdown | safe }}
    </div>
  </div>

  <script src="{% static 'mdeditor/js/jquery.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/editormd.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/marked.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/prettify.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/raphael.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/underscore.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/sequence-diagram.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/flowchart.min.js' %}"></script>
  <script src="{% static 'mdeditor/js/lib/jquery.flowchart.min.js' %}"></script>
  <script>
    $(function () {
        editormd.markdownToHTML("content", {
            emoji           : true,
            taskList        : true,
            tex             : true, 
            flowChart       : true,
            sequenceDiagram : true,
        });
        $(".reference-link").each(function (i,obj) {
          console.log(obj)
        })
    })
  </script>

{% endblock main %}

src/templates/summary_article.html
<!-- ベース読み込み -->
{% extends 'base.html' %} {% load static %}
{% load markdown_extras %}

  <!-- title挿入 -->
{% block title %}要約記事{% endblock %}
{% block meta %} 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
{% endblock meta %}

<body>
  {% block main %}
  <aside>
    <li>
      <a href="{% url 'summary_edit' chapter.id %}">要約編集</a>
    </li>
    {% if chapter.transcription_path %}
    <li>
      <a href="{% url 'download_transcription' chapter.id %}">文字起こしダウンロード</a>
    </li>
    {% endif %}
  </aside>
  
  {{ summary.summary_text | markdown | safe }}
  
  {% endblock main %}

src/templates/summary_edit.html
{% extends 'base.html' %} {% load static %}

{% block title %}要約編集{% endblock %}

{% block meta %} 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
{% endblock meta %}

{% block main %}
  <style>
      .edit-wrapper {
        margin-top: 20px;
        padding:0 30px;
        grid-column: 1 / 4;
        height: 100%;
        margin-top: 30px;
      }

  </style>
  <div class="title-menu-wrapper">
    <h1 class="video-title">{{ video.video_title }}</h1>
    <a href="{% url 'summary' video.id %}" class="menu-button">要約閲覧</a>
    <a href="{% url 'video' video.id %}" class="menu-button">動画閲覧</a>
    {% if video.transcription_path %}
      <a href="{% url 'download_transcription' video.id %}" class="menu-button">文字起こしダウンロード</a>
    {% endif %}
  </div>

  <div class="edit-wrapper">
    <form method="post">
      {% csrf_token %}
      {{ form.media }}
      {{ form.summary_text }}
      <button type="submit" class="submit-button">保存</button>
    </form>
  </div>

{% endblock main %}

src/templates/upload.html
{% extends 'base.html' %} {% load static %} 

{% block title %}動画アップロード{% endblock %}

{% block main %}
  <style>
    .submit-button {
      margin-top: 40px;
      width: 100%;
      font-size: 1.2em;
    }

    #id_video_path {
      border: 0;
      padding: 3px;
    }

    #uploading {
      display: none;
      margin-top: 20px;
      font-size: 1.5em;
      color: red;
    }

  </style>
  <div class="main-container">
    <h2>動画アップロード</h2>

    <form
      action="{% url 'upload' %}"
      method="post"
      enctype="multipart/form-data"
      name="form1"
      id="myform"
    >
      {% csrf_token %} 
      {{ form.as_p }}
      <button class="submit-button" id="upload-button">アップロード</button>
    </form>
    <div id="uploading">
      <p>アップロード中</p>
      <p>お待ちください</p>
    </div>
  </div>

  <script>
    document.getElementById('upload-button').addEventListener('click', function(event) {
      setTimeout( ()=>{
        document.getElementById('uploading').style.display = 'block'
      },1000);
    });
</script>
{% endblock main %}

src/templates/user.html
{% extends 'base.html' %} {% load static %}

{% block title %}アカウント管理{% endblock %}

{% block main %}
  <div class="main-container">
    <h1>{{user.username}}</h3>
    <h3>連絡先：{{user.email}}</h3>
    <h3>アカウント作成日：{{user.date_joined}}</h3>
    <h3><a href="/admin/" class="admin">管理者用ページ</a></h3>    
  </div>
{% endblock main %}